#ifndef REDMINERESTCLIENT_GLOBAL_H
#define REDMINERESTCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REDMINERESTCLIENT_LIBRARY)
#define REDMINERESTCLIENT_EXPORT Q_DECL_EXPORT
#else
#define REDMINERESTCLIENT_EXPORT Q_DECL_IMPORT
#endif

#endif // REDMINERESTCLIENT_GLOBAL_H
